# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowEwMyJw.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

class Ui_ui_MainWindow(object):
    def setupUi(self, ui_MainWindow):
        if not ui_MainWindow.objectName():
            ui_MainWindow.setObjectName(u"ui_MainWindow")
        ui_MainWindow.resize(961, 804)
        self.centralwidget = QWidget(ui_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 961, 711))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 321, 681))
        self.horizontalLayoutWidget_2 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 20, 321, 621))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.listWidget = QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget.setObjectName(u"listWidget")

        self.horizontalLayout_2.addWidget(self.listWidget)

        self.OpenInpProjectButton = QPushButton(self.groupBox)
        self.OpenInpProjectButton.setObjectName(u"OpenInpProjectButton")
        self.OpenInpProjectButton.setGeometry(QRect(0, 640, 81, 41))
        self.ListOptionsCombo = QComboBox(self.groupBox)
        self.ListOptionsCombo.addItem("")
        self.ListOptionsCombo.setObjectName(u"ListOptionsCombo")
        self.ListOptionsCombo.setGeometry(QRect(160, 645, 151, 31))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(83, 653, 81, 16))
        self.verticalLayoutWidget = QWidget(self.tab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(320, 340, 631, 341))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_2 = QTabWidget(self.verticalLayoutWidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.horizontalLayoutWidget_3 = QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(0, 0, 621, 281))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.OpenInpProjectButton_3 = QPushButton(self.tab_3)
        self.OpenInpProjectButton_3.setObjectName(u"OpenInpProjectButton_3")
        self.OpenInpProjectButton_3.setGeometry(QRect(364, 280, 150, 24))
        self.OpenInpProjectButton_2 = QPushButton(self.tab_3)
        self.OpenInpProjectButton_2.setObjectName(u"OpenInpProjectButton_2")
        self.OpenInpProjectButton_2.setGeometry(QRect(233, 280, 131, 24))
        self.Listallnodes_btnclick = QPushButton(self.tab_3)
        self.Listallnodes_btnclick.setObjectName(u"Listallnodes_btnclick")
        self.Listallnodes_btnclick.setGeometry(QRect(0, 280, 111, 24))
        self.ListOptionsCombo_2 = QComboBox(self.tab_3)
        self.ListOptionsCombo_2.addItem("")
        self.ListOptionsCombo_2.addItem("")
        self.ListOptionsCombo_2.addItem("")
        self.ListOptionsCombo_2.addItem("")
        self.ListOptionsCombo_2.setObjectName(u"ListOptionsCombo_2")
        self.ListOptionsCombo_2.setGeometry(QRect(112, 281, 121, 22))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.groupBox_3 = QGroupBox(self.tab_7)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 0, 621, 111))
        self.WNTR_list_WNTR_SHOW_RESULTSpushButton_7 = QPushButton(self.groupBox_3)
        self.WNTR_list_WNTR_SHOW_RESULTSpushButton_7.setObjectName(u"WNTR_list_WNTR_SHOW_RESULTSpushButton_7")
        self.WNTR_list_WNTR_SHOW_RESULTSpushButton_7.setGeometry(QRect(0, 20, 91, 71))
        self.WNTR_nodes_list_combo = QComboBox(self.groupBox_3)
        self.WNTR_nodes_list_combo.setObjectName(u"WNTR_nodes_list_combo")
        self.WNTR_nodes_list_combo.setGeometry(QRect(110, 40, 231, 22))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(110, 20, 49, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(360, 20, 49, 16))
        self.WNTR_links_list_combo = QComboBox(self.groupBox_3)
        self.WNTR_links_list_combo.setObjectName(u"WNTR_links_list_combo")
        self.WNTR_links_list_combo.setGeometry(QRect(360, 40, 241, 22))
        self.WNTR_SHowdemand_checkbox_4 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowdemand_checkbox_4.setObjectName(u"WNTR_SHowdemand_checkbox_4")
        self.WNTR_SHowdemand_checkbox_4.setGeometry(QRect(100, 70, 71, 20))
        self.WNTR_SHowhead_checkbox_5 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowhead_checkbox_5.setObjectName(u"WNTR_SHowhead_checkbox_5")
        self.WNTR_SHowhead_checkbox_5.setGeometry(QRect(167, 70, 71, 20))
        self.WNTR_SHowpressure_checkbox_6 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowpressure_checkbox_6.setObjectName(u"WNTR_SHowpressure_checkbox_6")
        self.WNTR_SHowpressure_checkbox_6.setGeometry(QRect(218, 70, 71, 20))
        self.WNTR_SHowquality_checkbox_7 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowquality_checkbox_7.setObjectName(u"WNTR_SHowquality_checkbox_7")
        self.WNTR_SHowquality_checkbox_7.setGeometry(QRect(280, 70, 61, 20))
        self.WNTR_SHowlinkquality_checkbox_5 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkquality_checkbox_5.setObjectName(u"WNTR_SHowlinkquality_checkbox_5")
        self.WNTR_SHowlinkquality_checkbox_5.setGeometry(QRect(360, 70, 61, 20))
        self.WNTR_SHowlinkflowrate_checkbox_6 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkflowrate_checkbox_6.setObjectName(u"WNTR_SHowlinkflowrate_checkbox_6")
        self.WNTR_SHowlinkflowrate_checkbox_6.setGeometry(QRect(420, 70, 71, 20))
        self.WNTR_SHowlinkvelocity_checkbox_7 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkvelocity_checkbox_7.setObjectName(u"WNTR_SHowlinkvelocity_checkbox_7")
        self.WNTR_SHowlinkvelocity_checkbox_7.setGeometry(QRect(486, 70, 61, 20))
        self.WNTR_SHowlinkheadloss_checkbox_8 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkheadloss_checkbox_8.setObjectName(u"WNTR_SHowlinkheadloss_checkbox_8")
        self.WNTR_SHowlinkheadloss_checkbox_8.setGeometry(QRect(550, 70, 71, 20))
        self.WNTR_SHowlinkfriction_checkbox_9 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkfriction_checkbox_9.setObjectName(u"WNTR_SHowlinkfriction_checkbox_9")
        self.WNTR_SHowlinkfriction_checkbox_9.setGeometry(QRect(360, 90, 71, 20))
        self.WNTR_SHowlinkreactionrate_checkbox_10 = QCheckBox(self.groupBox_3)
        self.WNTR_SHowlinkreactionrate_checkbox_10.setObjectName(u"WNTR_SHowlinkreactionrate_checkbox_10")
        self.WNTR_SHowlinkreactionrate_checkbox_10.setGeometry(QRect(420, 90, 91, 20))
        self.groupBox_4 = QGroupBox(self.tab_7)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 160, 621, 71))
        self.WNTRShowMapForTimeStamp_click = QPushButton(self.groupBox_4)
        self.WNTRShowMapForTimeStamp_click.setObjectName(u"WNTRShowMapForTimeStamp_click")
        self.WNTRShowMapForTimeStamp_click.setGeometry(QRect(0, 20, 101, 41))
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(110, 20, 71, 16))
        self.WNTR_SimSteps_text_box_2 = QLineEdit(self.groupBox_4)
        self.WNTR_SimSteps_text_box_2.setObjectName(u"WNTR_SimSteps_text_box_2")
        self.WNTR_SimSteps_text_box_2.setGeometry(QRect(180, 20, 61, 22))
        self.Savealldatacheckbox_2 = QCheckBox(self.groupBox_4)
        self.Savealldatacheckbox_2.setObjectName(u"Savealldatacheckbox_2")
        self.Savealldatacheckbox_2.setGeometry(QRect(110, 40, 71, 20))
        self.Savealldatacheckbox_3 = QCheckBox(self.groupBox_4)
        self.Savealldatacheckbox_3.setObjectName(u"Savealldatacheckbox_3")
        self.Savealldatacheckbox_3.setGeometry(QRect(180, 40, 71, 20))
        self.groupBox_5 = QGroupBox(self.tab_7)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 230, 621, 71))
        self.WNTR_simulate_pushButton_3 = QPushButton(self.groupBox_5)
        self.WNTR_simulate_pushButton_3.setObjectName(u"WNTR_simulate_pushButton_3")
        self.WNTR_simulate_pushButton_3.setGeometry(QRect(0, 20, 91, 41))
        self.WNTR_show_elevations_pushButton_4 = QPushButton(self.groupBox_5)
        self.WNTR_show_elevations_pushButton_4.setObjectName(u"WNTR_show_elevations_pushButton_4")
        self.WNTR_show_elevations_pushButton_4.setGeometry(QRect(90, 20, 101, 41))
        self.WNTR_show_popiulation_pushButton_5 = QPushButton(self.groupBox_5)
        self.WNTR_show_popiulation_pushButton_5.setObjectName(u"WNTR_show_popiulation_pushButton_5")
        self.WNTR_show_popiulation_pushButton_5.setGeometry(QRect(190, 20, 101, 41))
        self.WNTR_list_WNTR_NODES_AND_PIPES_pushButton_6 = QPushButton(self.tab_7)
        self.WNTR_list_WNTR_NODES_AND_PIPES_pushButton_6.setObjectName(u"WNTR_list_WNTR_NODES_AND_PIPES_pushButton_6")
        self.WNTR_list_WNTR_NODES_AND_PIPES_pushButton_6.setGeometry(QRect(200, 500, 101, 41))
        self.WNTR_saveasinopmodel_click_2 = QPushButton(self.tab_7)
        self.WNTR_saveasinopmodel_click_2.setObjectName(u"WNTR_saveasinopmodel_click_2")
        self.WNTR_saveasinopmodel_click_2.setGeometry(QRect(0, 110, 131, 41))
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.PandaPipes_simulate_btn = QGroupBox(self.tab_5)
        self.PandaPipes_simulate_btn.setObjectName(u"PandaPipes_simulate_btn")
        self.PandaPipes_simulate_btn.setGeometry(QRect(0, 0, 621, 311))
        self.TSNet_simulate_pushButton_4 = QPushButton(self.PandaPipes_simulate_btn)
        self.TSNet_simulate_pushButton_4.setObjectName(u"TSNet_simulate_pushButton_4")
        self.TSNet_simulate_pushButton_4.setGeometry(QRect(0, 20, 111, 41))
        self.PandaPipes_simulate_btn_2 = QGroupBox(self.PandaPipes_simulate_btn)
        self.PandaPipes_simulate_btn_2.setObjectName(u"PandaPipes_simulate_btn_2")
        self.PandaPipes_simulate_btn_2.setGeometry(QRect(0, 120, 621, 191))
        self.EpyT_simulate_pushButton_5 = QPushButton(self.PandaPipes_simulate_btn_2)
        self.EpyT_simulate_pushButton_5.setObjectName(u"EpyT_simulate_pushButton_5")
        self.EpyT_simulate_pushButton_5.setGeometry(QRect(0, 20, 181, 41))
        self.EpyT_showmodel_pushButton_6 = QPushButton(self.PandaPipes_simulate_btn_2)
        self.EpyT_showmodel_pushButton_6.setObjectName(u"EpyT_showmodel_pushButton_6")
        self.EpyT_showmodel_pushButton_6.setGeometry(QRect(180, 20, 111, 41))
        self.EpyT_showmodelelevation_pushButton_7 = QPushButton(self.PandaPipes_simulate_btn_2)
        self.EpyT_showmodelelevation_pushButton_7.setObjectName(u"EpyT_showmodelelevation_pushButton_7")
        self.EpyT_showmodelelevation_pushButton_7.setGeometry(QRect(290, 20, 121, 41))
        self.EpyT_showmodelresultsfortiemstamp_pushButton_8 = QPushButton(self.PandaPipes_simulate_btn_2)
        self.EpyT_showmodelresultsfortiemstamp_pushButton_8.setObjectName(u"EpyT_showmodelresultsfortiemstamp_pushButton_8")
        self.EpyT_showmodelresultsfortiemstamp_pushButton_8.setGeometry(QRect(0, 60, 151, 41))
        self.EpyT_timestamp_values_text_box_5 = QLineEdit(self.PandaPipes_simulate_btn_2)
        self.EpyT_timestamp_values_text_box_5.setObjectName(u"EpyT_timestamp_values_text_box_5")
        self.EpyT_timestamp_values_text_box_5.setGeometry(QRect(153, 71, 41, 21))
        self.EpyT_listnodelelevations_pushButton_8 = QPushButton(self.PandaPipes_simulate_btn_2)
        self.EpyT_listnodelelevations_pushButton_8.setObjectName(u"EpyT_listnodelelevations_pushButton_8")
        self.EpyT_listnodelelevations_pushButton_8.setGeometry(QRect(410, 20, 121, 41))
        self.groupBox_6 = QGroupBox(self.PandaPipes_simulate_btn_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 100, 611, 81))
        self.EpyT_showmodelresultsfortiemstamp_pushButton_9 = QPushButton(self.groupBox_6)
        self.EpyT_showmodelresultsfortiemstamp_pushButton_9.setObjectName(u"EpyT_showmodelresultsfortiemstamp_pushButton_9")
        self.EpyT_showmodelresultsfortiemstamp_pushButton_9.setGeometry(QRect(0, 20, 111, 41))
        self.label_12 = QLabel(self.groupBox_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(117, 30, 41, 16))
        self.EpyT_node_list_comboBox_3 = QComboBox(self.groupBox_6)
        self.EpyT_node_list_comboBox_3.setObjectName(u"EpyT_node_list_comboBox_3")
        self.EpyT_node_list_comboBox_3.setGeometry(QRect(150, 30, 191, 22))
        self.label_13 = QLabel(self.groupBox_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(340, 30, 41, 16))
        self.EpyT_link_list_comboBox_4 = QComboBox(self.groupBox_6)
        self.EpyT_link_list_comboBox_4.setObjectName(u"EpyT_link_list_comboBox_4")
        self.EpyT_link_list_comboBox_4.setGeometry(QRect(365, 30, 171, 22))
        self.EpyT_showlinkvelocity_checkBox = QCheckBox(self.groupBox_6)
        self.EpyT_showlinkvelocity_checkBox.setObjectName(u"EpyT_showlinkvelocity_checkBox")
        self.EpyT_showlinkvelocity_checkBox.setGeometry(QRect(410, 60, 61, 20))
        self.EpyT_showlinkflow_checkBox_2 = QCheckBox(self.groupBox_6)
        self.EpyT_showlinkflow_checkBox_2.setObjectName(u"EpyT_showlinkflow_checkBox_2")
        self.EpyT_showlinkflow_checkBox_2.setGeometry(QRect(360, 60, 61, 20))
        self.EpyT_showolinkverheadcheckBox_2 = QCheckBox(self.groupBox_6)
        self.EpyT_showolinkverheadcheckBox_2.setObjectName(u"EpyT_showolinkverheadcheckBox_2")
        self.EpyT_showolinkverheadcheckBox_2.setGeometry(QRect(470, 60, 81, 20))
        self.EpyT_shownodepressure_checkBox_3 = QCheckBox(self.groupBox_6)
        self.EpyT_shownodepressure_checkBox_3.setObjectName(u"EpyT_shownodepressure_checkBox_3")
        self.EpyT_shownodepressure_checkBox_3.setGeometry(QRect(110, 60, 71, 20))
        self.EpyT_shownodedemand_checkBox_4 = QCheckBox(self.groupBox_6)
        self.EpyT_shownodedemand_checkBox_4.setObjectName(u"EpyT_shownodedemand_checkBox_4")
        self.EpyT_shownodedemand_checkBox_4.setGeometry(QRect(176, 60, 71, 20))
        self.EpyT_shownodehead_checkBox_5 = QCheckBox(self.groupBox_6)
        self.EpyT_shownodehead_checkBox_5.setObjectName(u"EpyT_shownodehead_checkBox_5")
        self.EpyT_shownodehead_checkBox_5.setGeometry(QRect(243, 60, 51, 20))
        self.EpyT_shownodeinput_checkBox_6 = QCheckBox(self.groupBox_6)
        self.EpyT_shownodeinput_checkBox_6.setObjectName(u"EpyT_shownodeinput_checkBox_6")
        self.EpyT_shownodeinput_checkBox_6.setGeometry(QRect(293, 60, 51, 20))
        self.EpyTshowmapfortimestampcombo = QComboBox(self.PandaPipes_simulate_btn_2)
        self.EpyTshowmapfortimestampcombo.addItem("")
        self.EpyTshowmapfortimestampcombo.addItem("")
        self.EpyTshowmapfortimestampcombo.addItem("")
        self.EpyTshowmapfortimestampcombo.setObjectName(u"EpyTshowmapfortimestampcombo")
        self.EpyTshowmapfortimestampcombo.setGeometry(QRect(200, 70, 101, 22))
        self.TSNet_showmodelresultsfortiemstamp_pushButton_10 = QPushButton(self.PandaPipes_simulate_btn)
        self.TSNet_showmodelresultsfortiemstamp_pushButton_10.setObjectName(u"TSNet_showmodelresultsfortiemstamp_pushButton_10")
        self.TSNet_showmodelresultsfortiemstamp_pushButton_10.setGeometry(QRect(3, 63, 111, 31))
        self.TSNet_link_list_comboBox_5 = QComboBox(self.PandaPipes_simulate_btn)
        self.TSNet_link_list_comboBox_5.setObjectName(u"TSNet_link_list_comboBox_5")
        self.TSNet_link_list_comboBox_5.setGeometry(QRect(368, 73, 241, 22))
        self.TSNeT_node_list_comboBox_4 = QComboBox(self.PandaPipes_simulate_btn)
        self.TSNeT_node_list_comboBox_4.setObjectName(u"TSNeT_node_list_comboBox_4")
        self.TSNeT_node_list_comboBox_4.setGeometry(QRect(160, 70, 181, 22))
        self.label_15 = QLabel(self.PandaPipes_simulate_btn)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(343, 73, 41, 16))
        self.label_16 = QLabel(self.PandaPipes_simulate_btn)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(120, 73, 41, 16))
        self.TSNet_noidehead_checkBox_4 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_noidehead_checkBox_4.setObjectName(u"TSNet_noidehead_checkBox_4")
        self.TSNet_noidehead_checkBox_4.setGeometry(QRect(160, 100, 51, 20))
        self.TSNet_nodeemit_checkBox_5 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_nodeemit_checkBox_5.setObjectName(u"TSNet_nodeemit_checkBox_5")
        self.TSNet_nodeemit_checkBox_5.setGeometry(QRect(210, 100, 101, 20))
        self.TSNet_starthead_checkBox_5 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_starthead_checkBox_5.setObjectName(u"TSNet_starthead_checkBox_5")
        self.TSNet_starthead_checkBox_5.setGeometry(QRect(360, 90, 71, 20))
        self.TSNet_endhead_checkBox_6 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_endhead_checkBox_6.setObjectName(u"TSNet_endhead_checkBox_6")
        self.TSNet_endhead_checkBox_6.setGeometry(QRect(414, 90, 71, 20))
        self.TSNet_startvelociy_checkBox_7 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_startvelociy_checkBox_7.setObjectName(u"TSNet_startvelociy_checkBox_7")
        self.TSNet_startvelociy_checkBox_7.setGeometry(QRect(469, 90, 71, 20))
        self.TSNet_demanddischarge_checkBox_6 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_demanddischarge_checkBox_6.setObjectName(u"TSNet_demanddischarge_checkBox_6")
        self.TSNet_demanddischarge_checkBox_6.setGeometry(QRect(260, 100, 101, 20))
        self.TSNet_endvelcity_checkBox_8 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_endvelcity_checkBox_8.setObjectName(u"TSNet_endvelcity_checkBox_8")
        self.TSNet_endvelcity_checkBox_8.setGeometry(QRect(540, 90, 71, 20))
        self.TSNet_startflow_checkBox_9 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_startflow_checkBox_9.setObjectName(u"TSNet_startflow_checkBox_9")
        self.TSNet_startflow_checkBox_9.setGeometry(QRect(360, 105, 71, 20))
        self.TSNet_endflow_checkBox_10 = QCheckBox(self.PandaPipes_simulate_btn)
        self.TSNet_endflow_checkBox_10.setObjectName(u"TSNet_endflow_checkBox_10")
        self.TSNet_endflow_checkBox_10.setGeometry(QRect(413, 105, 71, 20))
        self.label_19 = QLabel(self.PandaPipes_simulate_btn)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(120, 31, 21, 16))
        self.Pollution_pollutionlevel_text_box_7 = QLineEdit(self.PandaPipes_simulate_btn)
        self.Pollution_pollutionlevel_text_box_7.setObjectName(u"Pollution_pollutionlevel_text_box_7")
        self.Pollution_pollutionlevel_text_box_7.setGeometry(QRect(140, 30, 41, 21))
        self.TSNet_resultstimeseries_pushButton_11 = QPushButton(self.PandaPipes_simulate_btn)
        self.TSNet_resultstimeseries_pushButton_11.setObjectName(u"TSNet_resultstimeseries_pushButton_11")
        self.TSNet_resultstimeseries_pushButton_11.setGeometry(QRect(2, 96, 111, 21))
        self.label_20 = QLabel(self.PandaPipes_simulate_btn)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(187, 31, 51, 16))
        self.Pollution_pollutionvelocity_text_box_8 = QLineEdit(self.PandaPipes_simulate_btn)
        self.Pollution_pollutionvelocity_text_box_8.setObjectName(u"Pollution_pollutionvelocity_text_box_8")
        self.Pollution_pollutionvelocity_text_box_8.setGeometry(QRect(234, 30, 41, 21))
        self.tabWidget_2.addTab(self.tab_5, "")

        self.verticalLayout.addWidget(self.tabWidget_2)

        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(320, 10, 631, 91))
        self.SimSteps_text_box = QLineEdit(self.groupBox_2)
        self.SimSteps_text_box.setObjectName(u"SimSteps_text_box")
        self.SimSteps_text_box.setGeometry(QRect(53, 20, 51, 22))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 23, 61, 16))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 23, 101, 16))
        self.Pywr_duration_units_combo = QComboBox(self.groupBox_2)
        self.Pywr_duration_units_combo.addItem("")
        self.Pywr_duration_units_combo.addItem("")
        self.Pywr_duration_units_combo.addItem("")
        self.Pywr_duration_units_combo.setObjectName(u"Pywr_duration_units_combo")
        self.Pywr_duration_units_combo.setGeometry(QRect(180, 20, 61, 22))
        self.groupBox_8 = QGroupBox(self.tab)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(320, 50, 631, 291))
        self.WNTR_waterintakeflag = QCheckBox(self.groupBox_8)
        self.WNTR_waterintakeflag.setObjectName(u"WNTR_waterintakeflag")
        self.WNTR_waterintakeflag.setGeometry(QRect(10, 20, 101, 20))
        self.groupBox_7 = QGroupBox(self.groupBox_8)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(0, 220, 631, 71))
        self.Savealldatacheckbox = QCheckBox(self.groupBox_7)
        self.Savealldatacheckbox.setObjectName(u"Savealldatacheckbox")
        self.Savealldatacheckbox.setGeometry(QRect(10, 20, 121, 20))
        self.WNTR_SimSave_text_box_2 = QLineEdit(self.groupBox_7)
        self.WNTR_SimSave_text_box_2.setObjectName(u"WNTR_SimSave_text_box_2")
        self.WNTR_SimSave_text_box_2.setGeometry(QRect(10, 41, 521, 21))
        self.WNTR_save_path_browse_pushButton_6 = QPushButton(self.groupBox_7)
        self.WNTR_save_path_browse_pushButton_6.setObjectName(u"WNTR_save_path_browse_pushButton_6")
        self.WNTR_save_path_browse_pushButton_6.setGeometry(QRect(540, 30, 71, 31))
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 40, 631, 181))
        self.verticalLayoutWidget_2 = QWidget(self.groupBox_9)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(9, 20, 621, 151))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_3 = QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.INP_files_checkstrangeelevations_button = QCheckBox(self.tab_12)
        self.INP_files_checkstrangeelevations_button.setObjectName(u"INP_files_checkstrangeelevations_button")
        self.INP_files_checkstrangeelevations_button.setGeometry(QRect(10, 10, 211, 20))
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.comboBox = QComboBox(self.tab_10)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(0, 20, 201, 22))
        self.label_7 = QLabel(self.tab_10)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 201, 16))
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.CloudsGenMethods_comboBox_3 = QComboBox(self.tab_6)
        self.CloudsGenMethods_comboBox_3.addItem("")
        self.CloudsGenMethods_comboBox_3.addItem("")
        self.CloudsGenMethods_comboBox_3.addItem("")
        self.CloudsGenMethods_comboBox_3.addItem("")
        self.CloudsGenMethods_comboBox_3.addItem("")
        self.CloudsGenMethods_comboBox_3.setObjectName(u"CloudsGenMethods_comboBox_3")
        self.CloudsGenMethods_comboBox_3.setGeometry(QRect(0, 20, 161, 22))
        self.label_14 = QLabel(self.tab_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 0, 161, 20))
        self.label_14.setFrameShape(QFrame.Shape.VLine)
        self.label_10 = QLabel(self.tab_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 22, 101, 16))
        self.WNTR_MaxRain_values_text_box_4 = QLineEdit(self.tab_6)
        self.WNTR_MaxRain_values_text_box_4.setObjectName(u"WNTR_MaxRain_values_text_box_4")
        self.WNTR_MaxRain_values_text_box_4.setGeometry(QRect(270, 20, 41, 21))
        self.Clouds_loadtimeseriesfromfile_pushButton_11 = QPushButton(self.tab_6)
        self.Clouds_loadtimeseriesfromfile_pushButton_11.setObjectName(u"Clouds_loadtimeseriesfromfile_pushButton_11")
        self.Clouds_loadtimeseriesfromfile_pushButton_11.setGeometry(QRect(0, 47, 101, 31))
        self.Clouds_Timeseries_text_box_4 = QLineEdit(self.tab_6)
        self.Clouds_Timeseries_text_box_4.setObjectName(u"Clouds_Timeseries_text_box_4")
        self.Clouds_Timeseries_text_box_4.setGeometry(QRect(103, 52, 501, 21))
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.label_8 = QLabel(self.tab_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 91, 16))
        self.comboBox_2 = QComboBox(self.tab_8)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(100, 5, 131, 22))
        self.label_9 = QLabel(self.tab_8)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 30, 191, 16))
        self.WNTR_SimSave_text_box_3 = QLineEdit(self.tab_8)
        self.WNTR_SimSave_text_box_3.setObjectName(u"WNTR_SimSave_text_box_3")
        self.WNTR_SimSave_text_box_3.setGeometry(QRect(0, 50, 611, 21))
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.WNTR_SimSave_text_box_5 = QLineEdit(self.tab_9)
        self.WNTR_SimSave_text_box_5.setObjectName(u"WNTR_SimSave_text_box_5")
        self.WNTR_SimSave_text_box_5.setGeometry(QRect(97, 18, 81, 20))
        self.label_11 = QLabel(self.tab_9)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 20, 101, 16))
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.Poolution_nodenames_text_box_6 = QLineEdit(self.tab_11)
        self.Poolution_nodenames_text_box_6.setObjectName(u"Poolution_nodenames_text_box_6")
        self.Poolution_nodenames_text_box_6.setGeometry(QRect(140, 0, 471, 20))
        self.Pollution_Noddenameslist_text = QLabel(self.tab_11)
        self.Pollution_Noddenameslist_text.setObjectName(u"Pollution_Noddenameslist_text")
        self.Pollution_Noddenameslist_text.setGeometry(QRect(4, 2, 101, 16))
        self.Pollution_Noddenameslist_text_2 = QLabel(self.tab_11)
        self.Pollution_Noddenameslist_text_2.setObjectName(u"Pollution_Noddenameslist_text_2")
        self.Pollution_Noddenameslist_text_2.setGeometry(QRect(4, 23, 141, 16))
        self.Pollution_introductiontimestamp_text_box_7 = QLineEdit(self.tab_11)
        self.Pollution_introductiontimestamp_text_box_7.setObjectName(u"Pollution_introductiontimestamp_text_box_7")
        self.Pollution_introductiontimestamp_text_box_7.setGeometry(QRect(140, 22, 471, 20))
        self.Pollution_Noddenameslist_text_3 = QLabel(self.tab_11)
        self.Pollution_Noddenameslist_text_3.setObjectName(u"Pollution_Noddenameslist_text_3")
        self.Pollution_Noddenameslist_text_3.setGeometry(QRect(5, 44, 61, 16))
        self.Pollution_duration_text_box_8 = QLineEdit(self.tab_11)
        self.Pollution_duration_text_box_8.setObjectName(u"Pollution_duration_text_box_8")
        self.Pollution_duration_text_box_8.setGeometry(QRect(140, 45, 471, 20))
        self.label_17 = QLabel(self.tab_11)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(4, 80, 81, 16))
        self.CloudsGenMethods_comboBox_4 = QComboBox(self.tab_11)
        self.CloudsGenMethods_comboBox_4.addItem("")
        self.CloudsGenMethods_comboBox_4.setObjectName(u"CloudsGenMethods_comboBox_4")
        self.CloudsGenMethods_comboBox_4.setGeometry(QRect(90, 77, 101, 22))
        self.label_18 = QLabel(self.tab_11)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(200, 80, 81, 16))
        self.Pollution_pollutionlevel_text_box_6 = QLineEdit(self.tab_11)
        self.Pollution_pollutionlevel_text_box_6.setObjectName(u"Pollution_pollutionlevel_text_box_6")
        self.Pollution_pollutionlevel_text_box_6.setGeometry(QRect(280, 78, 41, 21))
        self.tabWidget_3.addTab(self.tab_11, "")

        self.verticalLayout_2.addWidget(self.tabWidget_3)

        self.WNTR_waterpollutionflag_2 = QCheckBox(self.groupBox_8)
        self.WNTR_waterpollutionflag_2.setObjectName(u"WNTR_waterpollutionflag_2")
        self.WNTR_waterpollutionflag_2.setGeometry(QRect(110, 20, 101, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.ExitButton = QPushButton(self.centralwidget)
        self.ExitButton.setObjectName(u"ExitButton")
        self.ExitButton.setGeometry(QRect(880, 710, 75, 51))
        ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ui_MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 961, 22))
        ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(ui_MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        ui_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ui_MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ui_MainWindow)
    # setupUi

    def retranslateUi(self, ui_MainWindow):
        ui_MainWindow.setWindowTitle(QCoreApplication.translate("ui_MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("ui_MainWindow", u"Element list", None))
        self.OpenInpProjectButton.setText(QCoreApplication.translate("ui_MainWindow", u"Open file", None))
        self.ListOptionsCombo.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"Conduits", None))

        self.label.setText(QCoreApplication.translate("ui_MainWindow", u"Show options:", None))
        self.OpenInpProjectButton_3.setText(QCoreApplication.translate("ui_MainWindow", u"Reserved", None))
        self.OpenInpProjectButton_2.setText(QCoreApplication.translate("ui_MainWindow", u"Show graph in figure", None))
        self.Listallnodes_btnclick.setText(QCoreApplication.translate("ui_MainWindow", u"Show elements list", None))
        self.ListOptionsCombo_2.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"Conduits", None))
        self.ListOptionsCombo_2.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"Junctions", None))
        self.ListOptionsCombo_2.setItemText(2, QCoreApplication.translate("ui_MainWindow", u"Nodes", None))
        self.ListOptionsCombo_2.setItemText(3, QCoreApplication.translate("ui_MainWindow", u"Storages", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("ui_MainWindow", u"Graph overview", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("ui_MainWindow", u"SimulationS", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("ui_MainWindow", u"Show results for node/link", None))
        self.WNTR_list_WNTR_SHOW_RESULTSpushButton_7.setText(QCoreApplication.translate("ui_MainWindow", u"Show", None))
        self.label_4.setText(QCoreApplication.translate("ui_MainWindow", u"Node", None))
        self.label_5.setText(QCoreApplication.translate("ui_MainWindow", u"Link", None))
        self.WNTR_SHowdemand_checkbox_4.setText(QCoreApplication.translate("ui_MainWindow", u"Demand", None))
        self.WNTR_SHowhead_checkbox_5.setText(QCoreApplication.translate("ui_MainWindow", u"Head", None))
        self.WNTR_SHowpressure_checkbox_6.setText(QCoreApplication.translate("ui_MainWindow", u"Pressure", None))
        self.WNTR_SHowquality_checkbox_7.setText(QCoreApplication.translate("ui_MainWindow", u"Quality", None))
        self.WNTR_SHowlinkquality_checkbox_5.setText(QCoreApplication.translate("ui_MainWindow", u"Quality", None))
        self.WNTR_SHowlinkflowrate_checkbox_6.setText(QCoreApplication.translate("ui_MainWindow", u"Flowrate", None))
        self.WNTR_SHowlinkvelocity_checkbox_7.setText(QCoreApplication.translate("ui_MainWindow", u"Velocity", None))
        self.WNTR_SHowlinkheadloss_checkbox_8.setText(QCoreApplication.translate("ui_MainWindow", u"Headloss", None))
        self.WNTR_SHowlinkfriction_checkbox_9.setText(QCoreApplication.translate("ui_MainWindow", u"Friction", None))
        self.WNTR_SHowlinkreactionrate_checkbox_10.setText(QCoreApplication.translate("ui_MainWindow", u"Reaction rate", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("ui_MainWindow", u"Show map for timestamp", None))
        self.WNTRShowMapForTimeStamp_click.setText(QCoreApplication.translate("ui_MainWindow", u"Show", None))
        self.label_6.setText(QCoreApplication.translate("ui_MainWindow", u"Time stamp:", None))
        self.WNTR_SimSteps_text_box_2.setText(QCoreApplication.translate("ui_MainWindow", u"5000", None))
        self.Savealldatacheckbox_2.setText(QCoreApplication.translate("ui_MainWindow", u"Junctions", None))
        self.Savealldatacheckbox_3.setText(QCoreApplication.translate("ui_MainWindow", u"Pipes", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("ui_MainWindow", u"Show map for timestamp", None))
        self.WNTR_simulate_pushButton_3.setText(QCoreApplication.translate("ui_MainWindow", u"Simulate", None))
        self.WNTR_show_elevations_pushButton_4.setText(QCoreApplication.translate("ui_MainWindow", u"Show elevantions", None))
        self.WNTR_show_popiulation_pushButton_5.setText(QCoreApplication.translate("ui_MainWindow", u"Show population", None))
        self.WNTR_list_WNTR_NODES_AND_PIPES_pushButton_6.setText(QCoreApplication.translate("ui_MainWindow", u"List wntr nodes", None))
        self.WNTR_saveasinopmodel_click_2.setText(QCoreApplication.translate("ui_MainWindow", u"Save graph into *.inp", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("ui_MainWindow", u"wntr", None))
        self.PandaPipes_simulate_btn.setTitle(QCoreApplication.translate("ui_MainWindow", u"TSNet", None))
        self.TSNet_simulate_pushButton_4.setText(QCoreApplication.translate("ui_MainWindow", u"Simulate with TSNet", None))
        self.PandaPipes_simulate_btn_2.setTitle(QCoreApplication.translate("ui_MainWindow", u"EpyT", None))
        self.EpyT_simulate_pushButton_5.setText(QCoreApplication.translate("ui_MainWindow", u"Simulate with EpyT", None))
        self.EpyT_showmodel_pushButton_6.setText(QCoreApplication.translate("ui_MainWindow", u"Show EpyT model", None))
        self.EpyT_showmodelelevation_pushButton_7.setText(QCoreApplication.translate("ui_MainWindow", u"Show EpyT elevation", None))
        self.EpyT_showmodelresultsfortiemstamp_pushButton_8.setText(QCoreApplication.translate("ui_MainWindow", u"Show map for time stamp:", None))
        self.EpyT_timestamp_values_text_box_5.setText(QCoreApplication.translate("ui_MainWindow", u"1", None))
        self.EpyT_listnodelelevations_pushButton_8.setText(QCoreApplication.translate("ui_MainWindow", u"List nodes elevations", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("ui_MainWindow", u"Show time series", None))
        self.EpyT_showmodelresultsfortiemstamp_pushButton_9.setText(QCoreApplication.translate("ui_MainWindow", u"Show time series", None))
        self.label_12.setText(QCoreApplication.translate("ui_MainWindow", u"Node", None))
        self.label_13.setText(QCoreApplication.translate("ui_MainWindow", u"Link", None))
        self.EpyT_showlinkvelocity_checkBox.setText(QCoreApplication.translate("ui_MainWindow", u"Velocity", None))
        self.EpyT_showlinkflow_checkBox_2.setText(QCoreApplication.translate("ui_MainWindow", u"Flow", None))
        self.EpyT_showolinkverheadcheckBox_2.setText(QCoreApplication.translate("ui_MainWindow", u"Overhead", None))
        self.EpyT_shownodepressure_checkBox_3.setText(QCoreApplication.translate("ui_MainWindow", u"Pressure", None))
        self.EpyT_shownodedemand_checkBox_4.setText(QCoreApplication.translate("ui_MainWindow", u"Demand", None))
        self.EpyT_shownodehead_checkBox_5.setText(QCoreApplication.translate("ui_MainWindow", u"Head", None))
        self.EpyT_shownodeinput_checkBox_6.setText(QCoreApplication.translate("ui_MainWindow", u"Input", None))
        self.EpyTshowmapfortimestampcombo.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"Node pressure", None))
        self.EpyTshowmapfortimestampcombo.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"Node demand", None))
        self.EpyTshowmapfortimestampcombo.setItemText(2, QCoreApplication.translate("ui_MainWindow", u"Node head", None))

        self.TSNet_showmodelresultsfortiemstamp_pushButton_10.setText(QCoreApplication.translate("ui_MainWindow", u"Show time series", None))
        self.label_15.setText(QCoreApplication.translate("ui_MainWindow", u"Link", None))
        self.label_16.setText(QCoreApplication.translate("ui_MainWindow", u"Node", None))
        self.TSNet_noidehead_checkBox_4.setText(QCoreApplication.translate("ui_MainWindow", u"Head", None))
        self.TSNet_nodeemit_checkBox_5.setText(QCoreApplication.translate("ui_MainWindow", u"Emit", None))
        self.TSNet_starthead_checkBox_5.setText(QCoreApplication.translate("ui_MainWindow", u"S.head", None))
        self.TSNet_endhead_checkBox_6.setText(QCoreApplication.translate("ui_MainWindow", u"E.head", None))
        self.TSNet_startvelociy_checkBox_7.setText(QCoreApplication.translate("ui_MainWindow", u"S.velocity", None))
        self.TSNet_demanddischarge_checkBox_6.setText(QCoreApplication.translate("ui_MainWindow", u"Demand ", None))
        self.TSNet_endvelcity_checkBox_8.setText(QCoreApplication.translate("ui_MainWindow", u"E.velocity", None))
        self.TSNet_startflow_checkBox_9.setText(QCoreApplication.translate("ui_MainWindow", u"S.flow", None))
        self.TSNet_endflow_checkBox_10.setText(QCoreApplication.translate("ui_MainWindow", u"S.flow", None))
        self.label_19.setText(QCoreApplication.translate("ui_MainWindow", u"dt:", None))
        self.Pollution_pollutionlevel_text_box_7.setText(QCoreApplication.translate("ui_MainWindow", u"0.1", None))
        self.TSNet_resultstimeseries_pushButton_11.setText(QCoreApplication.translate("ui_MainWindow", u"List values", None))
        self.label_20.setText(QCoreApplication.translate("ui_MainWindow", u"Velocity:", None))
        self.Pollution_pollutionvelocity_text_box_8.setText(QCoreApplication.translate("ui_MainWindow", u"0.1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("ui_MainWindow", u"Other simulators", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("ui_MainWindow", u"Globals", None))
        self.SimSteps_text_box.setText(QCoreApplication.translate("ui_MainWindow", u"5000", None))
        self.label_2.setText(QCoreApplication.translate("ui_MainWindow", u"Sim.steps:", None))
        self.label_3.setText(QCoreApplication.translate("ui_MainWindow", u"Sim.step units:", None))
        self.Pywr_duration_units_combo.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"sec", None))
        self.Pywr_duration_units_combo.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"min", None))
        self.Pywr_duration_units_combo.setItemText(2, QCoreApplication.translate("ui_MainWindow", u"hours", None))

        self.groupBox_8.setTitle(QCoreApplication.translate("ui_MainWindow", u"Additional inputs", None))
        self.WNTR_waterintakeflag.setText(QCoreApplication.translate("ui_MainWindow", u"Add rain intake", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("ui_MainWindow", u"Results...", None))
        self.Savealldatacheckbox.setText(QCoreApplication.translate("ui_MainWindow", u"Save all data", None))
        self.WNTR_SimSave_text_box_2.setText(QCoreApplication.translate("ui_MainWindow", u"C:\\Tmp", None))
        self.WNTR_save_path_browse_pushButton_6.setText(QCoreApplication.translate("ui_MainWindow", u"Browse", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("ui_MainWindow", u"Settings", None))
        self.INP_files_checkstrangeelevations_button.setText(QCoreApplication.translate("ui_MainWindow", u"Check strange elevations of nodes", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), QCoreApplication.translate("ui_MainWindow", u"Joao_INP_files&Graphs", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"Clouds", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"Clouds+terrain", None))

        self.label_7.setText(QCoreApplication.translate("ui_MainWindow", u"Intake scenario", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), QCoreApplication.translate("ui_MainWindow", u"Scenario", None))
        self.CloudsGenMethods_comboBox_3.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"nlmpy", None))
        self.CloudsGenMethods_comboBox_3.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"trunc_power_law", None))
        self.CloudsGenMethods_comboBox_3.setItemText(2, QCoreApplication.translate("ui_MainWindow", u"lorenz_attractor", None))
        self.CloudsGenMethods_comboBox_3.setItemText(3, QCoreApplication.translate("ui_MainWindow", u"const", None))
        self.CloudsGenMethods_comboBox_3.setItemText(4, QCoreApplication.translate("ui_MainWindow", u"from_file", None))

        self.label_14.setText(QCoreApplication.translate("ui_MainWindow", u"Clouds generation methods", None))
        self.label_10.setText(QCoreApplication.translate("ui_MainWindow", u"Max h for clouds:", None))
        self.WNTR_MaxRain_values_text_box_4.setText(QCoreApplication.translate("ui_MainWindow", u"0.76", None))
        self.Clouds_loadtimeseriesfromfile_pushButton_11.setText(QCoreApplication.translate("ui_MainWindow", u"Load from file", None))
        self.Clouds_Timeseries_text_box_4.setText(QCoreApplication.translate("ui_MainWindow", u"C:\\Tmp", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("ui_MainWindow", u"Clouds", None))
        self.label_8.setText(QCoreApplication.translate("ui_MainWindow", u"Involved nodes:", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"All", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("ui_MainWindow", u"Specific", None))

        self.label_9.setText(QCoreApplication.translate("ui_MainWindow", u"Specific nodes (use \",\" as separator)", None))
        self.WNTR_SimSave_text_box_3.setText("")
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("ui_MainWindow", u"Nodes", None))
        self.WNTR_SimSave_text_box_5.setText(QCoreApplication.translate("ui_MainWindow", u"0.76", None))
        self.label_11.setText(QCoreApplication.translate("ui_MainWindow", u"Max h for terrain:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("ui_MainWindow", u"Terrain", None))
        self.Poolution_nodenames_text_box_6.setText("")
        self.Pollution_Noddenameslist_text.setText(QCoreApplication.translate("ui_MainWindow", u"Node names:", None))
        self.Pollution_Noddenameslist_text_2.setText(QCoreApplication.translate("ui_MainWindow", u"Introdcution time stamp:", None))
        self.Pollution_introductiontimestamp_text_box_7.setText("")
        self.Pollution_Noddenameslist_text_3.setText(QCoreApplication.translate("ui_MainWindow", u"Duration:", None))
        self.Pollution_duration_text_box_8.setText("")
        self.label_17.setText(QCoreApplication.translate("ui_MainWindow", u"Pattern shape", None))
        self.CloudsGenMethods_comboBox_4.setItemText(0, QCoreApplication.translate("ui_MainWindow", u"Rect", None))

        self.label_18.setText(QCoreApplication.translate("ui_MainWindow", u"Pollution level:", None))
        self.Pollution_pollutionlevel_text_box_6.setText(QCoreApplication.translate("ui_MainWindow", u"1", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), QCoreApplication.translate("ui_MainWindow", u"Pollution", None))
        self.WNTR_waterpollutionflag_2.setText(QCoreApplication.translate("ui_MainWindow", u"Add pollution", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("ui_MainWindow", u"\".inp\" Projects", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("ui_MainWindow", u"Tab 2", None))
        self.ExitButton.setText(QCoreApplication.translate("ui_MainWindow", u"Exit", None))
    # retranslateUi

